// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	Cik                    int64              `json:"cik"`
	Name                   string             `json:"name"`
	PeriodEnd              pgtype.Date        `json:"period_end"`
	Adsh                   string             `json:"adsh"`
	Assets                 *float64           `json:"assets"`
	Liabilities            *float64           `json:"liabilities"`
	StockholdersEquity     *float64           `json:"stockholders_equity"`
	NetIncome              *float64           `json:"net_income"`
	OperatingIncome        *float64           `json:"operating_income"`
	OperatingCashFlow      *float64           `json:"operating_cash_flow"`
	Capex                  *float64           `json:"capex"`
	Revenue                *float64           `json:"revenue"`
	Cash                   *float64           `json:"cash"`
	LongTermDebt           *float64           `json:"long_term_debt"`
	SharesOutstanding      *float64           `json:"shares_outstanding"`
	OperatingCashFlowPrior *float64           `json:"operating_cash_flow_prior"`
	CapexPrior             *float64           `json:"capex_prior"`
	NetIncomePrior         *float64           `json:"net_income_prior"`
	Eps                    *float64           `json:"eps"`
	Bvps                   *float64           `json:"bvps"`
	EpsGrowthRate          *float64           `json:"eps_growth_rate"`
	QualityScore           *float64           `json:"quality_score"`
	PassesHardFilter       bool               `json:"passes_hard_filter"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type IngestionRun struct {
	ID           int32              `json:"id"`
	Quarter      string             `json:"quarter"`
	CompanyCount int32              `json:"company_count"`
	IngestedAt   pgtype.Timestamptz `json:"ingested_at"`
}
