// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestIngestionQuarter = `-- name: GetLatestIngestionQuarter :one
SELECT quarter FROM ingestion_runs ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestIngestionQuarter(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getLatestIngestionQuarter)
	var quarter string
	err := row.Scan(&quarter)
	return quarter, err
}

const insertIngestionRun = `-- name: InsertIngestionRun :exec
INSERT INTO ingestion_runs (quarter, company_count)
VALUES ($1, $2)
`

type InsertIngestionRunParams struct {
	Quarter      string `json:"quarter"`
	CompanyCount int32  `json:"company_count"`
}

func (q *Queries) InsertIngestionRun(ctx context.Context, arg InsertIngestionRunParams) error {
	_, err := q.db.Exec(ctx, insertIngestionRun, arg.Quarter, arg.CompanyCount)
	return err
}

const listCandidates = `-- name: ListCandidates :many
SELECT cik, name, period_end, adsh,
       assets, liabilities, stockholders_equity,
       net_income, operating_income, operating_cash_flow, capex, revenue, cash, long_term_debt, shares_outstanding,
       operating_cash_flow_prior, capex_prior, net_income_prior,
       eps, bvps, eps_growth_rate, quality_score,
       passes_hard_filter, updated_at
FROM companies
WHERE passes_hard_filter = true
ORDER BY quality_score DESC NULLS LAST
LIMIT $1
`

// NULLS LAST: a passer can still have a nil quality_score (e.g. net_margin
// couldn't be computed even though ROE/FCF/D-E all passed), and Postgres's
// default for DESC is NULLS FIRST, which would wrongly rank it top.
func (q *Queries) ListCandidates(ctx context.Context, limit int32) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.Cik,
			&i.Name,
			&i.PeriodEnd,
			&i.Adsh,
			&i.Assets,
			&i.Liabilities,
			&i.StockholdersEquity,
			&i.NetIncome,
			&i.OperatingIncome,
			&i.OperatingCashFlow,
			&i.Capex,
			&i.Revenue,
			&i.Cash,
			&i.LongTermDebt,
			&i.SharesOutstanding,
			&i.OperatingCashFlowPrior,
			&i.CapexPrior,
			&i.NetIncomePrior,
			&i.Eps,
			&i.Bvps,
			&i.EpsGrowthRate,
			&i.QualityScore,
			&i.PassesHardFilter,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompany = `-- name: UpsertCompany :exec
INSERT INTO companies (
    cik, name, period_end, adsh,
    assets, liabilities, stockholders_equity,
    net_income, operating_income, operating_cash_flow, capex, revenue, cash, long_term_debt, shares_outstanding,
    operating_cash_flow_prior, capex_prior, net_income_prior,
    eps, bvps, eps_growth_rate, quality_score,
    passes_hard_filter, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21, $22,
    $23, now()
)
ON CONFLICT (cik) DO UPDATE SET
    name = EXCLUDED.name,
    period_end = EXCLUDED.period_end,
    adsh = EXCLUDED.adsh,
    assets = EXCLUDED.assets,
    liabilities = EXCLUDED.liabilities,
    stockholders_equity = EXCLUDED.stockholders_equity,
    net_income = EXCLUDED.net_income,
    operating_income = EXCLUDED.operating_income,
    operating_cash_flow = EXCLUDED.operating_cash_flow,
    capex = EXCLUDED.capex,
    revenue = EXCLUDED.revenue,
    cash = EXCLUDED.cash,
    long_term_debt = EXCLUDED.long_term_debt,
    shares_outstanding = EXCLUDED.shares_outstanding,
    operating_cash_flow_prior = EXCLUDED.operating_cash_flow_prior,
    capex_prior = EXCLUDED.capex_prior,
    net_income_prior = EXCLUDED.net_income_prior,
    eps = EXCLUDED.eps,
    bvps = EXCLUDED.bvps,
    eps_growth_rate = EXCLUDED.eps_growth_rate,
    quality_score = EXCLUDED.quality_score,
    passes_hard_filter = EXCLUDED.passes_hard_filter,
    updated_at = now()
`

type UpsertCompanyParams struct {
	Cik                    int64       `json:"cik"`
	Name                   string      `json:"name"`
	PeriodEnd              pgtype.Date `json:"period_end"`
	Adsh                   string      `json:"adsh"`
	Assets                 *float64    `json:"assets"`
	Liabilities            *float64    `json:"liabilities"`
	StockholdersEquity     *float64    `json:"stockholders_equity"`
	NetIncome              *float64    `json:"net_income"`
	OperatingIncome        *float64    `json:"operating_income"`
	OperatingCashFlow      *float64    `json:"operating_cash_flow"`
	Capex                  *float64    `json:"capex"`
	Revenue                *float64    `json:"revenue"`
	Cash                   *float64    `json:"cash"`
	LongTermDebt           *float64    `json:"long_term_debt"`
	SharesOutstanding      *float64    `json:"shares_outstanding"`
	OperatingCashFlowPrior *float64    `json:"operating_cash_flow_prior"`
	CapexPrior             *float64    `json:"capex_prior"`
	NetIncomePrior         *float64    `json:"net_income_prior"`
	Eps                    *float64    `json:"eps"`
	Bvps                   *float64    `json:"bvps"`
	EpsGrowthRate          *float64    `json:"eps_growth_rate"`
	QualityScore           *float64    `json:"quality_score"`
	PassesHardFilter       bool        `json:"passes_hard_filter"`
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error {
	_, err := q.db.Exec(ctx, upsertCompany,
		arg.Cik,
		arg.Name,
		arg.PeriodEnd,
		arg.Adsh,
		arg.Assets,
		arg.Liabilities,
		arg.StockholdersEquity,
		arg.NetIncome,
		arg.OperatingIncome,
		arg.OperatingCashFlow,
		arg.Capex,
		arg.Revenue,
		arg.Cash,
		arg.LongTermDebt,
		arg.SharesOutstanding,
		arg.OperatingCashFlowPrior,
		arg.CapexPrior,
		arg.NetIncomePrior,
		arg.Eps,
		arg.Bvps,
		arg.EpsGrowthRate,
		arg.QualityScore,
		arg.PassesHardFilter,
	)
	return err
}
